tenant:
  uuid: 5e0566fe-cf43-4451-9a6a-3908355da223
farms:
  - name: "Fair Oaks Farms - Site 4"
    description: ""
    uuid: f5a4b249-48dd-4956-9621-8a5a54303302
    default_stream: 7ea9b53b-749e-420b-891b-43b238f6144e
    time_zone: America/Chicago
    streams:
      - name: "Default Stream"
        description: ""
        uuid: 7ea9b53b-749e-420b-891b-43b238f6144e
        deafult: true
    cameras:
      - name: "Calf Box #1"
        description: ""
        uuid: 01dcccb4-83a1-4222-8fd0-70d9dc61ddb0
      - name: "Calf Box #2"
        description: ""
        uuid: 83318c59-63d6-42cd-99dc-8001f349d1bb
      - name: "Calving Pen #2"
        description: ""
        uuid: d3c03c88-e40f-4767-96a8-5f4b01740e7f
      - name: "Calving Pen #1"
        description: ""
        uuid: 8ee6d067-f789-43bd-a9af-b3efda7806ea
      - name: "Crowd Gate Back"
        description: ""
        uuid: dc4f4cb5-a2e5-4ca0-b3c0-8fbd4268a605
      - name: "Crowd Gate Front"
        description: ""
        uuid: 37199994-ed0b-4e83-b4e0-798e46d703f7
      - name: "Entry/Exit"
        description: ""
        uuid: 2c0c4930-eb02-4aeb-8977-f356d86484aa
      - name: "Load Chute"
        description: ""
        uuid: d3d803a7-faa7-4122-83d0-dc37e2c7f6dc
      - name: "Maternity East"
        description: ""
        uuid: a0410c4d-3e4e-4a78-ba9b-c938f6f7b38e
      - name: "Maternity West"
        description: ""
        uuid: 7c869e05-4fee-4fd9-be51-e4b2c5ca7a4e
      - name: "Matenity/Doors"
        description: ""
        uuid: 712da191-af81-4d4e-a151-be03a6a7fc4d
      - name: "N Freestall N Walkway"
        description: ""
        uuid: 70ed6c70-df4f-4761-bc9a-64fc50d79c83
      - name: "North Freestall South Walkway"
        description: ""
        uuid: 31e46a13-bc21-47d9-a82a-2aa776f54539
      - name: "NE #2"
        description: ""
        uuid: 0f2ed822-c63b-4f32-a09c-7478592fbb93
      - name: "NE #3"
        description: ""
        uuid: e80a3d5e-3f37-41bc-9e2b-a262e1d1b45a
      - name: "NE #4"
        description: ""
        uuid: 167af083-75d0-4255-b4e2-e629bbe5ecc0
      - name: "NE Center"
        description: ""
        uuid: dd0b524d-d0f5-4a88-b5c6-ad29eb41cd34
      - name: "NW Center"
        description: ""
        uuid: c79614c4-c6ca-4e3a-bf1a-48bfb85eef07
      - name: "NW #2"
        description: ""
        uuid: cdece925-e7df-4cc2-aef4-30f93c20f276
      - name: "NW #3"
        description: ""
        uuid: 210a0fea-be02-4509-a3f9-34d108011f89
      - name: "Palpitation Rail"
        description: ""
        uuid: 3f14f648-3e84-4f62-90e3-237d95993c20
      - name: "Parlor Holding"
        description: ""
        uuid: da9ce303-7aa0-46cb-b019-a13fba536ea7
      - name: "Post Dip"
        description: ""
        uuid: 7c078228-453e-43ca-bfa2-4cef1224b996
      - name: "Pre Dip"
        description: ""
        uuid: 93f38a00-c1f7-42e7-9456-d40ea4a6e27e
      - name: "Rotary Overview"
        description: ""
        uuid: bd1aa9d2-5a84-4091-a0c1-55f5ab1262b1
      - name: "SE #2"
        description: ""
        uuid: 744717f3-68d5-4ec2-b18d-aad4fc8a1389
      - name: "SE #3"
        description: ""
        uuid: a1c28737-013e-41b4-b00a-8587147a5e69
      - name: "SE Center"
        description: ""
        uuid: 09e85e85-b74b-40b2-bda5-9314d88b37ae
      - name: "Server Room"
        description: ""
        uuid: 06416c18-18a6-4c33-8829-22999d8b8630
        disabled: true
      - name: "Sick Cow Pen #2"
        description: ""
        uuid: a240fd7f-78eb-4cf4-b535-4f4cde95886d
      - name: "Sick Cow Pen"
        description: ""
        uuid: f5293b77-3b83-452d-978b-2275c4d9e014
      - name: "South Freestall Walkway North"
        description: ""
        uuid: 903b2f73-e0f7-4201-9eb2-2e07fc95281d
      - name: "SW #2"
        description: ""
        uuid: 0030b0e0-6438-4528-8573-16a822a9b5ca
      - name: "SW #3"
        description: ""
        uuid: 80c29d38-85fd-4db0-923c-36cc9bf0a756
      - name: "SW Center"
        description: ""
        uuid: 4c98742f-0441-4b05-8234-f405428ec91b
